### PR TITLE
SB-29457 Added env variable to mention content upload data limit

### PR DESCRIPTION
**Pull request by karthik-tarento**

### CODE REVIEW

**Comment by karthik-tarento** [comment]
@vinukumar-vs  Please review this PR

**Review by vinukumar-vs — APPROVED** [review]

**Comment by karthik-tarento** [comment]
@vinukumar-vs - can you create a new tag including this commit?

**Comment by karthik-tarento** [comment]
> @vinukumar-vs - can you create a new tag including this commit?

@vinukumar-vs -- have we created the tag for this in release-4.9 version ?? or this is planned for 4.10 version ?? Please provide the details.

**Comment by vinukumar-vs** [comment]
@karthik-tarento Release-4.8.5 tag is already created & went to prod as hot-fix. Refer the below tag
https://github.com/project-sunbird/knowledge-mw-service/releases/tag/release-4.8.5_RC1

**Pull request merged**
